name: Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: 0 1 1 * *

jobs:
  check:
    runs-on: ubuntu-latest

    steps:

    - name: Trigger build
      uses: peter-evans/repository-dispatch@v1
      with:
        token: ${{ secrets.ACTIONS_TRIGGER_PAT }}
        event-type: Source Code Update

    - name: Delete workflow runs
      uses: GitRML/delete-workflow-runs@main
      with:
        retain_days: 1
        keep_minimum_runs: 22
