name: Addon-Github

on:
  repository_dispatch:
  workflow_dispatch:

env:
  NAME: wp2static-addon-github
  REPO_URL: https://github.com/leonstafford/wp2static-addon-github.git
  REPO_BRANCH: master

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Checkout
      uses: actions/checkout@main
    
    - name: Initialization environment
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo mkdir -p /workdir
        sudo chown $USER:$GROUPS /workdir
        
    - name: Download the source code
      working-directory: /workdir
      run: |
        git clone $REPO_URL -b $REPO_BRANCH git
        zip -r $NAME.zip git
        mkdir ~/Downloads/
        mv $NAME.zip ~/Downloads/




    - name: Prepare for uploading
      working-directory: ~/Downloads/
      run: |
         unzip $NAME.zip
         rm $NAME.zip

    - name: Upload result
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.NAME }}.zip
        path: ~/Downloads/